'use client';

import {
  createContext,
  useContext,
  useState,
  useEffect,
  createElement,
  type ReactNode,
} from 'react';

// ─── Translation Dictionary ───────────────────────────────────────────────────

export const translations = {
  en: {
    nav: {
      home: 'Home',
      about: 'About',
      community: 'Community',
      organisation: 'Organisation',
      association: 'Association',
      supershop: 'Supershop',
      events: 'Events',
      blog: 'Blog',
      gallery: 'Gallery',
      contact: 'Contact',
      login: 'Login',
      register: 'Register',
      logout: 'Logout',
      settings: 'Settings',
      adminPanel: 'Admin Panel',
      backToSite: 'Back to Site',
      more: 'More',
      viewProfile: 'View Profile',
      lightMode: 'Light Mode',
      darkMode: 'Dark Mode',
    },
    auth: {
      loginTitle: 'Welcome back',
      loginSubtitle: 'Sign in to your 3ZF account',
      registerTitle: 'Create your account',
      registerSubtitle: 'Join the 3ZF community today',
      forgotTitle: 'Reset Password',
      forgotSubtitle: 'Enter your email to receive a reset code',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      fullName: 'Full Name',
      phone: 'Phone Number',
      forgotPassword: 'Forgot password?',
      noAccount: "Don't have an account?",
      hasAccount: 'Already have an account?',
      signIn: 'Sign In',
      createOne: 'Create one',
      signInLink: 'Sign in',
      continueBtn: 'Continue',
      sendOtp: 'Send Reset Code',
      verifyEmail: 'Verify your email',
      otpSubtitle: 'Enter the 6-digit code sent to your email',
      verifyBtn: 'Verify & Create Account',
      backToForm: 'Back to form',
      photoOptional: 'Photo (optional)',
      minPassword: 'Min. 6 characters',
      passwordsNoMatch: "Passwords don't match",
      accountCreated: 'Account created! Welcome to 3ZF',
      loginFailed: 'Login failed',
      registrationFailed: 'Registration failed',
      invalidOtp: 'Invalid or expired OTP',
      otpSent: 'OTP sent to your email!',
      resetPassword: 'Reset Password',
      newPassword: 'New Password',
      resetSuccess: 'Password Reset!',
      resetSuccessMsg: 'You can now sign in with your new password',
      numberCopied: 'Number copied!',
    },
    community: {
      title: 'Harmony Community',
      subtitle: 'Social Network',
      home: 'Home Feed',
      friends: 'Friends',
      groups: 'Groups',
      pages: 'Pages',
      saved: 'Saved',
      memories: 'Memories',
      whatsOnMind: "What's on your mind",
      createPost: 'Create Post',
      post: 'Post',
      posting: 'Posting...',
      photoVideo: 'Photo/Video',
      feeling: 'Feeling',
      location: 'Location',
      addToPost: 'Add to your post',
      public: 'Public',
      friends2: 'Friends',
      onlyMe: 'Only me',
      like: 'Like',
      comment: 'Comment',
      share: 'Share',
      reactions: 'reactions',
      comments: 'comments',
      shares: 'shares',
      writeComment: 'Write a comment...',
      addFriend: 'Add Friend',
      requested: 'Requested',
      message: 'Message',
      friendRequests: 'Friend Requests',
      confirm: 'Confirm',
      delete: 'Delete',
      contacts: 'Contacts',
      stories: 'Stories',
      createStory: 'Create Story',
      yourMessages: 'Your Messages',
      selectConv: 'Select a conversation to start chatting',
      messages: 'Messages',
      searchConv: 'Search conversations...',
      activeNow: 'Active now',
      isTyping: 'is typing...',
      send: 'Send',
      deleted: 'Message deleted',
      noFriends: 'No friends yet',
      noGroups: 'No groups found',
      noPages: 'No pages yet',
      joinGroup: 'Join',
      requestJoin: 'Request Join',
      joined: 'Joined',
      createGroup: 'Create Group',
      createPage: 'Create Page',
      follow: 'Follow',
      following: 'Following',
      posts: 'Posts',
      about: 'About',
      photos: 'Photos',
      editProfile: 'Edit Profile',
      noPosts: 'No posts yet',
      bio: 'Bio',
      born: 'Born',
      joinedLabel: 'Joined',
      searchPeople: 'Search people by name...',
      allFriends: 'All Friends',
      requests: 'Requests',
      findPeople: 'Find People',
      searchResults: 'No users found for',
      groupName: 'Group Name',
      groupDesc: 'Description',
      groupRules: 'Group Rules (one per line)',
      privacy: 'Privacy',
      publicGroup: 'Public',
      privateGroup: 'Private',
      anyoneSee: 'Anyone can see',
      membersOnly: 'Members only',
      addCoverPhoto: 'Add Cover Photo',
      notifications: 'Notifications',
      markAllRead: 'Mark all read',
      noNotifications: 'No notifications',
    },
    org: {
      title: 'Harmony Organisation',
      subtitle: 'Join our organisation, help others, make a difference',
      memberRegistration: 'Member Registration',
      donate: 'Donate',
      bookContact: 'Book Contact',
      pending: 'Pending',
      gallery: 'Gallery',
      becomeMember: '+ Become Member',
      memberApproved: 'Member',
      pendingApproval: 'Pending Approval',
      helpPost: 'Help Post',
      newHelpPost: 'Post New Help Request',
      helpPostSubtitle: 'Post with photo/video, 10 accepts unlock Trust Box',
      memberList: 'Member List',
      myDonations: 'My Donations',
      donateBtnLabel: 'Donate',
      registrationTitle: 'Harmony Organisation Membership',
      membershipFee: 'Membership Fee',
      personalInfo: 'Personal Information',
      address: 'Address',
      payment: 'Payment',
      done: 'Done',
      fullName: 'Full Name *',
      fatherName: "Father's Name *",
      motherName: "Mother's Name *",
      dob: 'Date of Birth *',
      religion: 'Religion *',
      phone: 'Mobile Number *',
      birthPlace: 'Birth Place *',
      presentAddress: 'Present Address *',
      district: 'District *',
      city: 'City/Upazila',
      village: 'Village',
      union: 'Union',
      municipality: 'Municipality',
      nidUpload: 'Voter ID / Birth Certificate (optional)',
      profilePhoto: 'Profile Photo (optional)',
      clickToUpload: 'Click to upload',
      paymentMethod: 'Payment Method',
      sendToNumber: 'Send payment to this number',
      paymentNumber: 'Your {method} Number *',
      transactionId: 'Transaction ID *',
      paymentAmount: 'Amount Sent *',
      oneTimePayment: 'One-time payment — Lifetime membership',
      submitApp: 'Submit Application',
      appSuccess: 'Application Submitted!',
      appSuccessMsg: 'Your membership application has been sent to admin.',
      appPending: 'Application in Progress',
      appPendingMsg: 'Your application is under review by admin.',
      helpTypes: {
        food: 'Food Aid',
        medical: 'Medical Aid',
        education: 'Education Aid',
        financial: 'Financial Aid',
        shelter: 'Shelter/Housing',
        emergency: 'Emergency Help',
        other: 'Other',
      },
      helpTitle: 'Title *',
      helpDesc: 'Description *',
      helpLocation: 'Location',
      helpAmount: 'Amount Needed',
      uploadMedia: 'Add Photo/Video (optional, max 5)',
      addMedia: 'Add photo or video',
      adminNote: 'Post goes to admin first. After approval all users will be notified.',
      submitHelp: 'Send Help Post',
      trustBox: 'Trust Box',
      trustProgress: '{n}/10',
      trustUnlocked: 'Unlocked!',
      trustMsg: '{n} more accepts to unlock Trust Box',
      trustUnlockedMsg: 'This person is verified as trusted',
      accepted: 'You Accepted',
      rejected: 'You Rejected',
      acceptBtn: 'Accept',
      rejectBtn: 'Reject',
      confirmResponse: 'Confirm',
      cancelBtn: 'Cancel',
      acceptMsg: 'You are accepting',
      rejectMsg: 'You are rejecting',
      msgOptional: 'Message (optional)...',
      noHelpPosts: 'No help posts yet',
      noMembers: 'No approved members',
      noDonations: 'No donations',
      firstDonate: 'Make First Donation',
      donation: 'Donation',
      donatePage: 'Donate to Organisation',
      donateSubtitle: 'Your help moves us forward',
      quickAmount: 'Quick Select Amount',
      customAmount: 'Or enter custom amount',
      purpose: 'Purpose',
      purposePlaceholder: 'Select purpose',
      donorName: 'Your Name (optional)',
      anonymousTip: 'Leave empty to donate anonymously',
      donateBtn: 'Donate',
      thankYou: 'Thank You!',
      donationSubmitted: 'Your donation has been submitted. Will confirm after verification.',
      donateAgain: 'Donate Again',
      amountLabel: 'Amount (BDT)',
      confirming: 'Confirmed',
      verifying: 'Verifying',
      failed: 'Failed',
    },
    shop: {
      title: 'Harmony Supershop',
      subtitle: 'Best products, best prices',
      cart: 'Cart',
      checkout: 'Checkout',
      orders: 'My Orders',
      membership: 'Membership',
      products: 'Products',
      addToCart: 'Add to Cart',
      buyNow: 'Buy Now',
      inStock: 'In Stock',
      outOfStock: 'Out of Stock',
      reviews: 'Customer Reviews',
      writeReview: 'Write a Review',
      noReviews: 'No reviews yet',
      categories: 'Categories',
      sortBy: 'Sort By',
      newest: 'Newest',
      priceLow: 'Price: Low to High',
      priceHigh: 'Price: High to Low',
      productsFound: 'products found',
      noProducts: 'No products found',
      cartEmpty: 'Cart is empty',
      startShopping: 'Start Shopping',
      total: 'Total',
      subtotal: 'Subtotal',
      deliveryCharge: 'Delivery Charge',
      freeDelivery: 'Free Delivery',
      proceedCheckout: 'Proceed to Checkout',
      deliveryAddress: 'Delivery Address',
      recipientName: 'Recipient Name *',
      mobileNumber: 'Mobile Number *',
      fullAddress: 'Full Address *',
      city: 'City/Upazila *',
      postalCode: 'Postal Code',
      placeOrder: 'Place Order',
      orderSuccess: 'Order Successful!',
      orderSuccessMsg: 'Payment will be confirmed after verification.',
      orderStatus: 'Order Status',
      orderDate: 'Order Date',
      trackingNo: 'Tracking:',
      paymentStatus: 'Payment Status',
      moreShop: 'Shop More',
      myOrders: 'My Orders',
      premiumMember: 'Premium Member',
      memberBenefits: 'Premium Benefits',
      onlyFee: 'Only',
      lifetimeMem: 'One-time payment — Lifetime',
      memberIdLabel: 'Member ID',
      joinDate: 'Join Date',
      validThru: 'Valid Through',
      lifetime: 'Lifetime',
      appSubmitted: 'Application Submitted!',
      adminReview: 'Admin will review and confirm.',
      pendingApproval: 'Application Pending',
    },
    common: {
      loading: 'Loading...',
      error: 'Something went wrong',
      retry: 'Retry',
      save: 'Save Changes',
      saving: 'Saving...',
      saved: 'Saved!',
      cancel: 'Cancel',
      close: 'Close',
      confirm: 'Confirm',
      delete: 'Delete',
      edit: 'Edit',
      view: 'View',
      submit: 'Submit',
      submitting: 'Submitting...',
      success: 'Success!',
      failed: 'Failed',
      yes: 'Yes',
      no: 'No',
      ok: 'OK',
      search: 'Search',
      filter: 'Filter',
      sort: 'Sort',
      noData: 'No data found',
      noResults: 'No results',
      seeAll: 'See All',
      loadMore: 'Load More',
      backBtn: 'Back',
      nextBtn: 'Next',
      prevBtn: 'Previous',
      required: 'Required',
      optional: 'Optional',
      copy: 'Copy',
      copied: 'Copied!',
      upload: 'Upload',
      uploading: 'Uploading...',
      approved: 'Approved',
      pending: 'Pending',
      rejected: 'Rejected',
      active: 'Active',
      inactive: 'Inactive',
      all: 'All',
      none: 'None',
      date: 'Date',
      time: 'Time',
      status: 'Status',
      action: 'Action',
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      address: 'Address',
      amount: 'Amount',
      method: 'Method',
      language: 'Language',
      theme: 'Theme',
      pageNotFound: 'Page not found',
    },
    settings: {
      title: 'Settings',
      profile: 'Profile',
      privacy: 'Privacy & Security',
      notifications: 'Notifications',
      appearance: 'Appearance',
      language: 'Language',
      account: 'Account',
      editProfile: 'Edit Profile',
      changePhoto: 'Change photo',
      gender: 'Gender',
      male: 'Male',
      female: 'Female',
      other: 'Other',
      website: 'Website',
      bio: 'Bio',
      bioPlaceholder: 'Tell people about yourself...',
      locationPlaceholder: 'City, Country',
      websitePlaceholder: 'https://...',
      dangerZone: 'Danger Zone',
      deleteAccount: 'Delete Account',
      deleteAccountDesc: 'Once you submit a delete request, an admin will permanently delete your account.',
      requestDeletion: 'Request Account Deletion',
      deleteReason: 'Tell us why (optional)',
      confirmDelete: 'Confirm Delete Request',
      lightMode: 'Light',
      darkMode: 'Dark',
      systemMode: 'System',
      chooseTheme: 'Choose your preferred theme',
      paymentHistory: 'Payment History',
    },
    events: {
      title: 'Upcoming Events',
      subtitle: 'Browse and attend events',
      rsvp: 'RSVP',
      attending: 'Attending',
      noEvents: 'No events',
      attendees: 'attending',
      location: 'Location',
      date: 'Date',
    },
    blog: {
      title: 'Blog',
      subtitle: 'Latest articles and news',
      allLang: 'All',
      english: 'English',
      bangla: 'Bengali',
      by: 'by',
      views: 'Views',
      likes: 'Likes',
      writeComment: 'Write a comment...',
      postComment: 'Post',
      noComments: 'No comments yet. Be the first!',
      backToBlog: 'Back to Blog',
    },
    gallery: {
      title: 'Gallery',
      subtitle: 'Our memories and moments',
    },
    contact: {
      title: 'Contact Us',
      subtitle: "We're ready to help",
      name: 'Name *',
      email: 'Email *',
      phone: 'Phone',
      subject: 'Subject *',
      message: 'Message *',
      send: 'Send Message',
      sending: 'Sending...',
      sent: 'Message Sent!',
      sentMsg: 'We will contact you soon.',
      sendAnother: 'Send Another',
    },
    admin: {
      dashboard: 'Dashboard',
      users: 'Users',
      organisation: 'Organisation',
      shopMembers: 'Shop Members',
      association: 'Association',
      products: 'Products',
      orders: 'Orders',
      payments: 'Payments',
      events: 'Events',
      blogs: 'Blogs',
      gallery: 'Gallery',
      contact: 'Contact',
      deleteRequests: 'Delete Requests',
      totalUsers: 'Total Users',
      orgMembers: 'Org Members',
      pendingMembers: 'Pending Members',
      totalRevenue: 'Total Revenue',
      recentUsers: 'Recent Users',
      viewAll: 'View all',
      approve: 'Approve',
      reject: 'Reject',
      suspend: 'Suspend',
      activate: 'Activate',
      approveMember: 'Approve & Notify All',
      noApplications: 'No pending applications',
      adminPanel: '3ZF Admin',
      controlPanel: 'Control Panel v3',
    },
    about: {
      title: 'About Us',
      mission: 'Our Mission',
      missionText: 'We believe technology can simplify lives. Through Harmony Community, Organisation, Association, and Supershop we have created a complete digital ecosystem.',
      values: 'Our Values',
      service: 'Service Spirit',
      serviceDesc: 'We work for the welfare of every person in society.',
      unity: 'Unity',
      unityDesc: 'Together we can bring great change.',
      goal: 'Goal',
      goalDesc: 'We move forward with clear goals and plans.',
      excellence: 'Excellence',
      excellenceDesc: 'We work while maintaining the best standards.',
      transparency: 'Transparency',
      transparencyDesc: 'Full transparency in all activities is our policy.',
      trust: 'Trust',
      trustDesc: 'Trust and confidence is our greatest asset.',
      journey: 'Our Journey',
      stats: {
        activeMembers: 'Active Members',
        orgMembers: 'Org Members',
        events: 'Events Organized',
        products: 'Products Listed',
      },
    },
  },

  bn: {
    nav: {
      home: 'হোম',
      about: 'আমাদের সম্পর্কে',
      community: 'কমিউনিটি',
      organisation: 'অর্গানাইজেশন',
      association: 'অ্যাসোসিয়েশন',
      supershop: 'সুপারশপ',
      events: 'ইভেন্ট',
      blog: 'ব্লগ',
      gallery: 'গ্যালারি',
      contact: 'যোগাযোগ',
      login: 'লগইন',
      register: 'রেজিস্টার',
      logout: 'লগআউট',
      settings: 'সেটিংস',
      adminPanel: 'অ্যাডমিন প্যানেল',
      backToSite: 'সাইটে ফিরে যান',
      more: 'আরো',
      viewProfile: 'প্রোফাইল দেখুন',
      lightMode: 'লাইট মোড',
      darkMode: 'ডার্ক মোড',
    },
    auth: {
      loginTitle: 'স্বাগতম',
      loginSubtitle: 'আপনার 3ZF অ্যাকাউন্টে সাইন ইন করুন',
      registerTitle: 'অ্যাকাউন্ট তৈরি করুন',
      registerSubtitle: '3ZF কমিউনিটিতে যোগ দিন',
      forgotTitle: 'পাসওয়ার্ড রিসেট',
      forgotSubtitle: 'রিসেট কোড পেতে ইমেইল দিন',
      email: 'ইমেইল',
      password: 'পাসওয়ার্ড',
      confirmPassword: 'পাসওয়ার্ড নিশ্চিত করুন',
      fullName: 'পূর্ণ নাম',
      phone: 'মোবাইল নম্বর',
      forgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?',
      noAccount: 'অ্যাকাউন্ট নেই?',
      hasAccount: 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
      signIn: 'সাইন ইন',
      createOne: 'তৈরি করুন',
      signInLink: 'সাইন ইন করুন',
      continueBtn: 'পরবর্তী',
      sendOtp: 'রিসেট কোড পাঠান',
      verifyEmail: 'ইমেইল যাচাই করুন',
      otpSubtitle: 'আপনার ইমেইলে পাঠানো ৬-সংখ্যার কোড দিন',
      verifyBtn: 'যাচাই করুন এবং অ্যাকাউন্ট তৈরি করুন',
      backToForm: 'ফর্মে ফিরুন',
      photoOptional: 'ছবি (ঐচ্ছিক)',
      minPassword: 'সর্বনিম্ন ৬ অক্ষর',
      passwordsNoMatch: 'পাসওয়ার্ড মেলেনি',
      accountCreated: 'অ্যাকাউন্ট তৈরি হয়েছে! 3ZF-এ স্বাগতম',
      loginFailed: 'লগইন ব্যর্থ',
      registrationFailed: 'রেজিস্ট্রেশন ব্যর্থ',
      invalidOtp: 'OTP ভুল বা মেয়াদ শেষ',
      otpSent: 'আপনার ইমেইলে OTP পাঠানো হয়েছে!',
      resetPassword: 'পাসওয়ার্ড রিসেট',
      newPassword: 'নতুন পাসওয়ার্ড',
      resetSuccess: 'পাসওয়ার্ড রিসেট সফল!',
      resetSuccessMsg: 'এখন নতুন পাসওয়ার্ড দিয়ে সাইন ইন করুন',
      numberCopied: 'নম্বর কপি হয়েছে!',
    },
    community: {
      title: 'হারমনি কমিউনিটি',
      subtitle: 'সামাজিক নেটওয়ার্ক',
      home: 'হোম ফিড',
      friends: 'বন্ধু',
      groups: 'গ্রুপ',
      pages: 'পেজ',
      saved: 'সেভ করা',
      memories: 'স্মৃতি',
      whatsOnMind: 'কী ভাবছেন',
      createPost: 'পোস্ট তৈরি করুন',
      post: 'পোস্ট',
      posting: 'পোস্ট হচ্ছে...',
      photoVideo: 'ছবি/ভিডিও',
      feeling: 'অনুভূতি',
      location: 'অবস্থান',
      addToPost: 'পোস্টে যোগ করুন',
      public: 'সবার জন্য',
      friends2: 'বন্ধুদের জন্য',
      onlyMe: 'শুধু আমি',
      like: 'লাইক',
      comment: 'মন্তব্য',
      share: 'শেয়ার',
      reactions: 'রিঅ্যাকশন',
      comments: 'মন্তব্য',
      shares: 'শেয়ার',
      writeComment: 'মন্তব্য লিখুন...',
      addFriend: 'বন্ধু যোগ করুন',
      requested: 'রিকোয়েস্ট পাঠানো',
      message: 'বার্তা',
      friendRequests: 'বন্ধুত্বের অনুরোধ',
      confirm: 'নিশ্চিত',
      delete: 'মুছুন',
      contacts: 'যোগাযোগ',
      stories: 'স্টোরি',
      createStory: 'স্টোরি তৈরি করুন',
      yourMessages: 'আপনার বার্তাগুলো',
      selectConv: 'চ্যাট শুরু করতে কথোপকথন নির্বাচন করুন',
      messages: 'বার্তা',
      searchConv: 'কথোপকথন খুঁজুন...',
      activeNow: 'এখন সক্রিয়',
      isTyping: 'টাইপ করছেন...',
      send: 'পাঠান',
      deleted: 'বার্তাটি মুছে দেওয়া হয়েছে',
      noFriends: 'এখনো কোনো বন্ধু নেই',
      noGroups: 'কোনো গ্রুপ পাওয়া যায়নি',
      noPages: 'এখনো কোনো পেজ নেই',
      joinGroup: 'যোগ দিন',
      requestJoin: 'যোগ দিতে অনুরোধ',
      joined: 'যোগ দেওয়া হয়েছে',
      createGroup: 'গ্রুপ তৈরি করুন',
      createPage: 'পেজ তৈরি করুন',
      follow: 'ফলো করুন',
      following: 'ফলো করছেন',
      posts: 'পোস্ট',
      about: 'পরিচিতি',
      photos: 'ছবি',
      editProfile: 'প্রোফাইল সম্পাদনা',
      noPosts: 'কোনো পোস্ট নেই',
      bio: 'বায়ো',
      born: 'জন্ম',
      joinedLabel: 'যোগদান',
      searchPeople: 'নাম দিয়ে মানুষ খুঁজুন...',
      allFriends: 'সব বন্ধু',
      requests: 'অনুরোধ',
      findPeople: 'মানুষ খুঁজুন',
      searchResults: 'কোনো ব্যবহারকারী পাওয়া যায়নি',
      groupName: 'গ্রুপের নাম',
      groupDesc: 'বিবরণ',
      groupRules: 'গ্রুপের নিয়ম (প্রতি লাইনে একটি)',
      privacy: 'গোপনীয়তা',
      publicGroup: 'পাবলিক',
      privateGroup: 'প্রাইভেট',
      anyoneSee: 'সবাই দেখতে পাবে',
      membersOnly: 'শুধু সদস্যরা',
      addCoverPhoto: 'কভার ফটো যোগ করুন',
      notifications: 'নোটিফিকেশন',
      markAllRead: 'সব পঠিত করুন',
      noNotifications: 'কোনো নোটিফিকেশন নেই',
    },
    org: {
      title: 'হারমনি অর্গানাইজেশন',
      subtitle: 'সংগঠনের সাথে যুক্ত হন, সাহায্য করুন, পরিবর্তন আনুন',
      memberRegistration: 'সদস্য নিবন্ধন',
      donate: 'ডোনেশন',
      bookContact: 'বুক কনট্যাক্ট',
      pending: 'পেন্ডিং',
      gallery: 'গ্যালারি',
      becomeMember: '+ সদস্য হন',
      memberApproved: 'সদস্য',
      pendingApproval: 'অনুমোদন প্রতীক্ষায়',
      helpPost: 'সাহায্যের পোস্ট',
      newHelpPost: 'নতুন সাহায্যের পোস্ট করুন',
      helpPostSubtitle: 'ছবি/ভিডিও সহ পোস্ট করুন, ১০ জন Accept করলে Trust Box খুলবে',
      memberList: 'সদস্য তালিকা',
      myDonations: 'আমার ডোনেশন',
      donateBtnLabel: 'ডোনেশন করুন',
      registrationTitle: 'Harmony Organisation সদস্যতা',
      membershipFee: 'সদস্যতা ফি',
      personalInfo: 'ব্যক্তিগত তথ্য',
      address: 'ঠিকানা',
      payment: 'পেমেন্ট',
      done: 'সম্পন্ন',
      fullName: 'পূর্ণ নাম *',
      fatherName: 'বাবার নাম *',
      motherName: 'মায়ের নাম *',
      dob: 'জন্ম তারিখ *',
      religion: 'ধর্ম *',
      phone: 'মোবাইল নম্বর *',
      birthPlace: 'জন্মস্থান *',
      presentAddress: 'বর্তমান ঠিকানা *',
      district: 'জেলা *',
      city: 'শহর/উপজেলা',
      village: 'গ্রাম',
      union: 'ইউনিয়ন',
      municipality: 'পৌরসভা',
      nidUpload: 'ভোটার আইডি / জন্ম নিবন্ধন (ঐচ্ছিক)',
      profilePhoto: 'প্রোফাইল ছবি (ঐচ্ছিক)',
      clickToUpload: 'ক্লিক করে আপলোড করুন',
      paymentMethod: 'পেমেন্ট পদ্ধতি',
      sendToNumber: 'এই নম্বরে পেমেন্ট করুন',
      paymentNumber: 'আপনার নম্বর *',
      transactionId: 'ট্রানজেকশন আইডি *',
      paymentAmount: 'পাঠানো পরিমাণ *',
      oneTimePayment: 'একবারের পেমেন্ট — আজীবন সদস্যতা',
      submitApp: 'আবেদন জমা দিন',
      appSuccess: 'আবেদন সফল!',
      appSuccessMsg: 'আপনার সদস্যতার আবেদন ও পেমেন্ট তথ্য অ্যাডমিনের কাছে পাঠানো হয়েছে।',
      appPending: 'আবেদন প্রক্রিয়াধীন',
      appPendingMsg: 'পেমেন্ট যাচাইয়ের পর সদস্যপদ দেওয়া হবে।',
      helpTypes: {
        food: 'খাদ্য সহায়তা',
        medical: 'চিকিৎসা সহায়তা',
        education: 'শিক্ষা সহায়তা',
        financial: 'আর্থিক সহায়তা',
        shelter: 'আশ্রয়/বাসস্থান',
        emergency: 'জরুরি সাহায্য',
        other: 'অন্যান্য',
      },
      helpTitle: 'শিরোনাম *',
      helpDesc: 'বিস্তারিত বিবরণ *',
      helpLocation: 'অবস্থান',
      helpAmount: 'প্রয়োজনীয় পরিমাণ',
      uploadMedia: 'ছবি/ভিডিও যোগ করুন (ঐচ্ছিক, সর্বোচ্চ ৫টি)',
      addMedia: 'ছবি বা ভিডিও যোগ করুন',
      adminNote: 'পোস্ট অ্যাডমিনের কাছে পাঠানো হবে। অনুমোদনের পর সব ব্যবহারকারী দেখতে পাবেন।',
      submitHelp: 'সাহায্যের পোস্ট পাঠান',
      trustBox: 'Trust Box',
      trustProgress: '{n}/10',
      trustUnlocked: 'খুলে গেছে!',
      trustMsg: 'আর {n} জন Accept করলে Trust Box খুলবে',
      trustUnlockedMsg: 'এই পোস্টকারী বিশ্বস্ত হিসেবে স্বীকৃত',
      accepted: 'আপনি Accept করেছেন',
      rejected: 'আপনি Reject করেছেন',
      acceptBtn: 'Accept',
      rejectBtn: 'Reject',
      confirmResponse: 'নিশ্চিত করুন',
      cancelBtn: 'বাতিল',
      acceptMsg: 'Accept করছেন',
      rejectMsg: 'Reject করছেন',
      msgOptional: 'বার্তা (ঐচ্ছিক)...',
      noHelpPosts: 'এখনো কোনো সাহায্যের পোস্ট নেই',
      noMembers: 'কোনো অনুমোদিত সদস্য নেই',
      noDonations: 'কোনো ডোনেশন নেই',
      firstDonate: 'প্রথম ডোনেশন করুন',
      donation: 'ডোনেশন',
      donatePage: 'সংগঠনে ডোনেশন করুন',
      donateSubtitle: 'আপনার সাহায্য আমাদের এগিয়ে যেতে সাহায্য করে',
      quickAmount: 'দ্রুত পরিমাণ বেছে নিন',
      customAmount: 'অথবা নিজে পরিমাণ লিখুন',
      purpose: 'উদ্দেশ্য',
      purposePlaceholder: 'উদ্দেশ্য নির্বাচন করুন',
      donorName: 'আপনার নাম (ঐচ্ছিক)',
      anonymousTip: 'বেনামে রাখতে চাইলে খালি রাখুন',
      donateBtn: 'ডোনেট করুন',
      thankYou: 'ধন্যবাদ!',
      donationSubmitted: 'আপনার ডোনেশন জমা হয়েছে। যাচাইয়ের পর নিশ্চিত হবে।',
      donateAgain: 'আরো ডোনেশন করুন',
      amountLabel: 'পরিমাণ (BDT)',
      confirming: 'নিশ্চিত',
      verifying: 'যাচাই চলছে',
      failed: 'ব্যর্থ',
    },
    shop: {
      title: 'হারমনি সুপারশপ',
      subtitle: 'সেরা পণ্য, সেরা দামে',
      cart: 'কার্ট',
      checkout: 'চেকআউট',
      orders: 'আমার অর্ডার',
      membership: 'সদস্যতা',
      products: 'পণ্য',
      addToCart: 'কার্টে যোগ করুন',
      buyNow: 'এখনই কিনুন',
      inStock: 'স্টকে আছে',
      outOfStock: 'স্টক নেই',
      reviews: 'গ্রাহক পর্যালোচনা',
      writeReview: 'পর্যালোচনা লিখুন',
      noReviews: 'এখনো কোনো পর্যালোচনা নেই',
      categories: 'বিভাগ',
      sortBy: 'সাজান',
      newest: 'সর্বশেষ',
      priceLow: 'দাম: কম থেকে বেশি',
      priceHigh: 'দাম: বেশি থেকে কম',
      productsFound: 'টি পণ্য পাওয়া গেছে',
      noProducts: 'কোনো পণ্য পাওয়া যায়নি',
      cartEmpty: 'কার্ট খালি',
      startShopping: 'শপিং করতে যান',
      total: 'সর্বমোট',
      subtotal: 'সাবটোটাল',
      deliveryCharge: 'ডেলিভারি চার্জ',
      freeDelivery: 'বিনামূল্যে ডেলিভারি',
      proceedCheckout: 'চেকআউটে যান',
      deliveryAddress: 'ডেলিভারি ঠিকানা',
      recipientName: 'প্রাপকের নাম *',
      mobileNumber: 'মোবাইল নম্বর *',
      fullAddress: 'সম্পূর্ণ ঠিকানা *',
      city: 'শহর/উপজেলা *',
      postalCode: 'পোস্টাল কোড',
      placeOrder: 'অর্ডার করুন',
      orderSuccess: 'অর্ডার সফল!',
      orderSuccessMsg: 'পেমেন্ট যাচাইয়ের পর প্রক্রিয়া শুরু হবে।',
      orderStatus: 'অর্ডার অবস্থা',
      orderDate: 'অর্ডারের তারিখ',
      trackingNo: 'ট্র্যাকিং:',
      paymentStatus: 'পেমেন্ট অবস্থা',
      moreShop: 'আরো শপিং',
      myOrders: 'আমার অর্ডার',
      premiumMember: 'প্রিমিয়াম সদস্য',
      memberBenefits: 'প্রিমিয়াম সুবিধাসমূহ',
      onlyFee: 'মাত্র',
      lifetimeMem: 'একবারের পেমেন্ট — আজীবন',
      memberIdLabel: 'সদস্য ID',
      joinDate: 'যোগদানের তারিখ',
      validThru: 'মেয়াদ',
      lifetime: 'আজীবন',
      appSubmitted: 'আবেদন সফল!',
      adminReview: 'অ্যাডমিন যাচাই করার পর সদস্য হবেন।',
      pendingApproval: 'আবেদন প্রক্রিয়াধীন',
    },
    common: {
      loading: 'লোড হচ্ছে...',
      error: 'কিছু একটা ভুল হয়েছে',
      retry: 'আবার চেষ্টা করুন',
      save: 'পরিবর্তন সংরক্ষণ',
      saving: 'সংরক্ষণ হচ্ছে...',
      saved: 'সংরক্ষিত!',
      cancel: 'বাতিল',
      close: 'বন্ধ করুন',
      confirm: 'নিশ্চিত করুন',
      delete: 'মুছুন',
      edit: 'সম্পাদনা',
      view: 'দেখুন',
      submit: 'জমা দিন',
      submitting: 'জমা হচ্ছে...',
      success: 'সফল!',
      failed: 'ব্যর্থ',
      yes: 'হ্যাঁ',
      no: 'না',
      ok: 'ঠিক আছে',
      search: 'খুঁজুন',
      filter: 'ফিল্টার',
      sort: 'সাজান',
      noData: 'কোনো তথ্য পাওয়া যায়নি',
      noResults: 'কোনো ফলাফল নেই',
      seeAll: 'সব দেখুন',
      loadMore: 'আরো লোড করুন',
      backBtn: 'পেছনে',
      nextBtn: 'পরবর্তী',
      prevBtn: 'পূর্ববর্তী',
      required: 'প্রয়োজনীয়',
      optional: 'ঐচ্ছিক',
      copy: 'কপি',
      copied: 'কপি হয়েছে!',
      upload: 'আপলোড',
      uploading: 'আপলোড হচ্ছে...',
      approved: 'অনুমোদিত',
      pending: 'অপেক্ষমাণ',
      rejected: 'প্রত্যাখ্যাত',
      active: 'সক্রিয়',
      inactive: 'নিষ্ক্রিয়',
      all: 'সব',
      none: 'কিছু নেই',
      date: 'তারিখ',
      time: 'সময়',
      status: 'অবস্থা',
      action: 'পদক্ষেপ',
      name: 'নাম',
      email: 'ইমেইল',
      phone: 'ফোন',
      address: 'ঠিকানা',
      amount: 'পরিমাণ',
      method: 'পদ্ধতি',
      language: 'ভাষা',
      theme: 'থিম',
      pageNotFound: 'পেজ খুঁজে পাওয়া যায়নি',
    },
    settings: {
      title: 'সেটিংস',
      profile: 'প্রোফাইল',
      privacy: 'গোপনীয়তা ও নিরাপত্তা',
      notifications: 'নোটিফিকেশন',
      appearance: 'চেহারা',
      language: 'ভাষা',
      account: 'অ্যাকাউন্ট',
      editProfile: 'প্রোফাইল সম্পাদনা',
      changePhoto: 'ছবি পরিবর্তন করুন',
      gender: 'লিঙ্গ',
      male: 'পুরুষ',
      female: 'মহিলা',
      other: 'অন্যান্য',
      website: 'ওয়েবসাইট',
      bio: 'বায়ো',
      bioPlaceholder: 'নিজের সম্পর্কে লিখুন...',
      locationPlaceholder: 'শহর, দেশ',
      websitePlaceholder: 'https://...',
      dangerZone: 'বিপদ অঞ্চল',
      deleteAccount: 'অ্যাকাউন্ট মুছুন',
      deleteAccountDesc: 'Delete request পাঠালে অ্যাডমিন যাচাই করে স্থায়ীভাবে মুছে দেবেন।',
      requestDeletion: 'অ্যাকাউন্ট মুছে দিতে অনুরোধ করুন',
      deleteReason: 'কারণ বলুন (ঐচ্ছিক)',
      confirmDelete: 'Delete Request নিশ্চিত করুন',
      lightMode: 'লাইট',
      darkMode: 'ডার্ক',
      systemMode: 'সিস্টেম',
      chooseTheme: 'আপনার পছন্দের থিম বেছে নিন',
      paymentHistory: 'পেমেন্ট ইতিহাস',
    },
    events: {
      title: 'আসছে ইভেন্টগুলো',
      subtitle: 'ইভেন্ট দেখুন ও যোগ দিন',
      rsvp: 'RSVP',
      attending: 'যোগ দিচ্ছেন',
      noEvents: 'কোনো ইভেন্ট নেই',
      attendees: 'জন যোগ দিচ্ছেন',
      location: 'স্থান',
      date: 'তারিখ',
    },
    blog: {
      title: 'ব্লগ',
      subtitle: 'সর্বশেষ নিবন্ধ ও সংবাদ',
      allLang: 'সব',
      english: 'English',
      bangla: 'বাংলা',
      by: 'লিখেছেন',
      views: 'ভিউ',
      likes: 'লাইক',
      writeComment: 'মন্তব্য লিখুন...',
      postComment: 'পোস্ট',
      noComments: 'কোনো মন্তব্য নেই। প্রথম হন!',
      backToBlog: 'ব্লগে ফিরুন',
    },
    gallery: {
      title: 'গ্যালারি',
      subtitle: 'আমাদের স্মৃতি ও মুহূর্তগুলো',
    },
    contact: {
      title: 'যোগাযোগ করুন',
      subtitle: 'আমরা সাহায্য করতে প্রস্তুত',
      name: 'নাম *',
      email: 'ইমেইল *',
      phone: 'ফোন',
      subject: 'বিষয় *',
      message: 'বার্তা *',
      send: 'বার্তা পাঠান',
      sending: 'পাঠানো হচ্ছে...',
      sent: 'বার্তা পাঠানো হয়েছে!',
      sentMsg: 'আমরা শীঘ্রই যোগাযোগ করব।',
      sendAnother: 'আরো বার্তা পাঠান',
    },
    admin: {
      dashboard: 'ড্যাশবোর্ড',
      users: 'ব্যবহারকারী',
      organisation: 'অর্গানাইজেশন',
      shopMembers: 'শপ সদস্য',
      association: 'অ্যাসোসিয়েশন',
      products: 'পণ্য',
      orders: 'অর্ডার',
      payments: 'পেমেন্ট',
      events: 'ইভেন্ট',
      blogs: 'ব্লগ',
      gallery: 'গ্যালারি',
      contact: 'যোগাযোগ',
      deleteRequests: 'মুছে দেওয়ার অনুরোধ',
      totalUsers: 'মোট ব্যবহারকারী',
      orgMembers: 'অর্গ সদস্য',
      pendingMembers: 'অপেক্ষমাণ সদস্য',
      totalRevenue: 'মোট রাজস্ব',
      recentUsers: 'সাম্প্রতিক ব্যবহারকারী',
      viewAll: 'সব দেখুন',
      approve: 'অনুমোদন',
      reject: 'প্রত্যাখ্যান',
      suspend: 'স্থগিত',
      activate: 'সক্রিয় করুন',
      approveMember: 'অনুমোদন করুন ও সবাইকে জানান',
      noApplications: 'কোনো অপেক্ষমাণ আবেদন নেই',
      adminPanel: '3ZF অ্যাডমিন',
      controlPanel: 'কন্ট্রোল প্যানেল v3',
    },
    about: {
      title: 'আমাদের সম্পর্কে',
      mission: 'আমাদের লক্ষ্য',
      missionText: 'আমরা বিশ্বাস করি প্রযুক্তি মানুষের জীবনকে সহজ করতে পারে। Harmony Community, Organisation, Association এবং Supershop এর মাধ্যমে আমরা একটি সম্পূর্ণ ডিজিটাল ইকোসিস্টেম তৈরি করেছি।',
      values: 'আমাদের মূল্যবোধ',
      service: 'সেবার মনোভাব',
      serviceDesc: 'সমাজের প্রতিটি মানুষের কল্যাণে আমরা কাজ করি।',
      unity: 'একতা',
      unityDesc: 'একতাবদ্ধ হয়ে আমরা বড় পরিবর্তন আনতে পারি।',
      goal: 'লক্ষ্যমাত্রা',
      goalDesc: 'স্পষ্ট লক্ষ্য ও পরিকল্পনা নিয়ে আমরা এগিয়ে যাই।',
      excellence: 'উৎকর্ষতা',
      excellenceDesc: 'সেরা মান বজায় রেখে আমরা কাজ করে যাই।',
      transparency: 'স্বচ্ছতা',
      transparencyDesc: 'সকল কার্যক্রমে পূর্ণ স্বচ্ছতা আমাদের নীতি।',
      trust: 'বিশ্বস্ততা',
      trustDesc: 'বিশ্বাস ও আস্থাই আমাদের সবচেয়ে বড় সম্পদ।',
      journey: 'আমাদের যাত্রা',
      stats: {
        activeMembers: 'সক্রিয় সদস্য',
        orgMembers: 'সংগঠনের সদস্য',
        events: 'আয়োজিত ইভেন্ট',
        products: 'তালিকাভুক্ত পণ্য',
      },
    },
  },
} as const;

// ─── Types ────────────────────────────────────────────────────────────────────

export type Lang         = 'en' | 'bn';
export type Translations = typeof translations.en;

// ─── Context ──────────────────────────────────────────────────────────────────

interface I18nContextType {
  lang:    Lang;
  setLang: (l: Lang) => void;
  t:       Translations;
}

const I18nContext = createContext<I18nContextType>({
  lang:    'en',
  setLang: () => {},
  t:       translations.en,
});

// ─── Font helper ──────────────────────────────────────────────────────────────

function applyLangFont(lang: Lang): void {
  if (typeof document === 'undefined') return;
  document.documentElement.lang = lang === 'bn' ? 'bn' : 'en';
  if (lang === 'bn') {
    document.body.classList.add('lang-bn');
    document.body.classList.remove('lang-en');
    document.body.style.fontFamily =
      'var(--font-noto-bengali), Noto Sans Bengali, sans-serif';
  } else {
    document.body.classList.add('lang-en');
    document.body.classList.remove('lang-bn');
    document.body.style.fontFamily = 'var(--font-inter), Inter, sans-serif';
  }
}

// ─── Provider ─────────────────────────────────────────────────────────────────

export function I18nProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>('en');

  useEffect(() => {
    const saved = localStorage.getItem('3zf-lang') as Lang | null;
    if (saved === 'en' || saved === 'bn') {
      setLangState(saved);
      applyLangFont(saved);
    }
  }, []);

  const setLang = (l: Lang): void => {
    setLangState(l);
    localStorage.setItem('3zf-lang', l);
    applyLangFont(l);
  };

  const contextValue: I18nContextType = {
    lang,
    setLang,
    t: translations[lang] as Translations,
  };

  // No JSX — use createElement so this file can stay as .ts
  return createElement(I18nContext.Provider, { value: contextValue }, children);
}

// ─── Hooks ────────────────────────────────────────────────────────────────────

export const useI18n = (): I18nContextType => useContext(I18nContext);
export const useLang = (): Lang             => useContext(I18nContext).lang;
export const useT   = (): Translations      => useContext(I18nContext).t;